name: practice
run-name: ${{github.actor}} is testing github action
on: [push]
jobs:
  Explore-github:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this job is running on ${{runner.os}} by github"
          echo "the name of your branch is ${{github.ref}} and your repo ${{github.repository}}"
      - name: checkout repository code
        uses: actions/checkout@v2
      - run: |
          echo "the repo has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: list files
        run: |
          ls ${{github.workspace}}